---
- name: Install package from a specific repository
  community.general.apk:
    name: geoip
    state: latest
    update_cache: yes

  community.general.apk:
    name: tar
    state: latest
    update_cache: yes

  community.general.apk:
    name: unzip
    state: latest
    update_cache: yes


# - name: Gets GEO IP Update tarball
#   get_url:
#     url: '{{ maxmind_update_package_alpine }}'
#     dest: "/srv/{{ maxmind_update_directory_alpine }}.tar.gz"

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /srv/{{ maxmind_update_directory_alpine }}
    state: directory
    mode: '0755'

- name: Download GEO IP Tarball
  ansible.builtin.get_url:
    # src: /srv/{{ maxmind_update_directory_alpine }}.tar.gz
    url: "{{ maxmind_update_package_alpine }}"
    dest: /tmp/tarball.tgz

- name: Unarchive GEO IP Tarball
  ansible.builtin.shell:
    chdir: /tmp
    cmd: "tar xvfz /tmp/tarball.tgz"

- name: Copy geoipupdate to /usr/bin
  ansible.builtin.copy:
    src: /tmp/{{ maxmind_update_directory_alpine }}/geoipupdate
    dest: /usr/bin
    mode: '0755'
    remote_src: yes
